import { defineStorage } from "@aws-amplify/backend";

/**
 * Box to Cloud Storage Configuration
 *
 * S3 bucket for storing page images extracted from scanned PDFs.
 * Structure: {tenant}/{box}/{set}/page_{pageNumber}.png
 * Example: wth/001/box_001_20251110_173850/page_0001.png
 *
 * Access: Images are served via pre-signed URLs generated by the
 * getPageImageUrl Lambda function, which verifies tenant authorization.
 * Direct S3 access is not granted to users.
 */
export const storage = defineStorage({
  name: "box2cloud-pages",
  // No direct user access - all access is through pre-signed URLs
  // generated by the getPageImageUrl Lambda function
});
